

	<div id="main">
		
		
		

    <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    
                    <h2 class="intro-text text-center">
                        <?php echo '<form action=' .$this->url(array('controller' => 'index',
		     										'action' => 'catalog'), 'default', true). ' method = "post" >'; ?>
		     										

			
		                      <center>
								  
								 <label id = "labelMaxPrice" for="maxPrice">Max Price</label>
                                 <input id="maxPrice" name="maxPrice" type="text" size="25">
								  
								  
				  
								  
								  <?php echo  $this->printCitySelect($this->housesListForSelect);   ?>
								  

								  
								  
								  <select id = "selectSize" name="size" size="1">
                	                  <option value="any" selected>Any size</option>
                	                  <option value="small">Small</option>
                	                  <option value="medium"> Medium</option>
                	                  <option value="large">Large</option>
            	                  </select>
								  
								  
								  
								
		                     <input type = "submit" value="Search"></center>
	
	
	                         </form>
                    </h2>
                    <hr>
                </div>
               
                <div class="col-md-6">
                    
                   
                   
                   

          <div class="row-fluid">
			  
			  <table>
				  <tr>
			  <?php 
			  
			  $this->headScript()->appendScript('catalogHouses()', 'text/javascript');
			  
			  echo $this->printHousesCatalog($this);
			  
			
            
            ?>
            
            </tr>
            
            </table>

            
         </div>
           
                   
                   
                    
                    
                </div>
                <div class="clearfix"></div>
                
               
            </div>
        </div>

        

    </div>
   
   

   


		

	</div>


























