

	<div id="main">
		


    <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    
                    <h2 class="intro-text text-center">
                        
                    </h2>
                  
                </div>
               
                <div class="col-md-6">
                    
                   
                   
                   

          <div class="row-fluid">
			  
	
	
			  
			  	<?php
		
		$this->headScript()->appendScript('faq()', 'text/javascript');

	
		 
		foreach ($this->faqList as $faq) {
			
			echo "<strong><p class = 'question' id = ".$faq->id.  ">".$faq->question. "</p></strong>";
			echo "<p class = 'answer' id = ".$faq->id.  ">".$faq->answer. "</p>";
	
			
		}
		
		
		
		
		?>

			  
	
            
         </div>
           
                   
                   
                    
                    
                </div>
                <div class="clearfix"></div>
            </div>
        </div>

        

    </div>
   
    

   


		

	</div>


























