
	<div id="main">
		
		
		<div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12 text-center">
                    <div id="carousel-example-generic" class="carousel slide">
                        <!-- Indicators -->
                        <ol class="carousel-indicators hidden-xs">
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                        </ol>

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner">
                            <div class="item active">
                                <img class="img-responsive img-full" src="<?php echo $this->baseUrl('img/'.$this->house->picture1) ?>" alt="">
                            </div>
                            <div class="item">
                                <img class="img-responsive img-full" src="<?php echo $this->baseUrl('img/'.$this->house->picture2) ?>" alt="">
                            </div>
                            <div class="item">
                                <img class="img-responsive img-full" src="<?php echo $this->baseUrl('img/'.$this->house->picture3) ?>" alt="">
                            </div>
                        </div>

                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                            <span class="icon-prev"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                            <span class="icon-next"></span>
                        </a>
                    </div>
                    <br><br>
                    <h1 class="brand-name"><?php echo $this->house->location. " - ". number_format($this->house->price). " £"    ?></h1>
                    <hr class="tagline-divider">
                    <h3>
                        <small>
                            <h5>contact: </h5><strong> <?php echo $this->house->phone  ?> - <a href = "mailto:<?php echo $this->house->email  ?>"> <?php echo $this->house->email  ?></a> </strong>
                        </small>
                    </h3>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                <p>
                 <?php echo $this->formatText($this->house->description); ?>
                    </p>
                </div>
            </div>
        </div>

        

    </div>
    <!-- /.container -->

    

    

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>
		

	</div>






