
<div id = "main">
    <div class="container">

        

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
					
					<?php 
					
					if ($this->registration == false || is_null($this->registration)) {
						
						
						
						
						 echo "<h6 class='intro-text text-center'> Don't you have an account? 

                    <strong><a href=" . $this->url(array(
                        'controller' => 'index',
                        'action'     => 'login',
                        'registration' => true), 
                        'default',true
                    ) .
                   ">Register now!</a></strong>

                    </h6>
                    <hr>
                    
                    
                    <center>" .
                    
                    
                    
                     $this->loginForm
                    
                    
                    
                    
                    . " </center>"; 
                    
						
	
						
					}
					
					
					
					else {
						
						
						echo "<h6 class='intro-text text-center'>Registration Form</h6>
                    <hr>
                    
                    
                    <center>" .
                    
                    
                    
                     $this->registrationForm
                    
                    
                    
                    
                    . " </center>";
						
						
						
						
						
						
						
						
						
						
						
					}
					
					
					
					
					
					  ?>
					  
					  
                    
                   
                    
                    
                    
                    
                    
                    
                    
                    
                    
                   </div>
            </div>
        </div>

    </div>


    


</div>
