

	<div id="main">
		


    <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    
                    <h2 class="intro-text text-center">
                        
                    </h2>
                  
                </div>
               
                <div class="col-md-6">
                    
                   <?php 
			  
			  $this->headScript()->appendScript('myHouses()', 'text/javascript');

            ?>
                   
                   

          <div class="row-fluid">
			  
		   

			  
	
            
         </div>
           
                   
                   
                    
                    
                </div>
                <div class="clearfix">
                
                <form>
                
                 <table id = "MyTable">
				  
				  <tr><th class = "myHeader">House</th><th class = "myHeader">Location</th><th class = "myHeader">Price</th><th class = "myHeader">Ft²</th><th class = "myHeader" colspan = 2>Options</th></tr>
			  
	
	
		<?php 
		
		
		
		
		foreach ($this->myHousesList as $myHouse) {
			
			echo "<tr><td class = 'dataImg'><a href = '". $this->url(array('controller' => 'index',
		                                                     'action' => 'infohouse', 
									                         'houseId' => $myHouse->id), 'default', true) ."'><img src = '". $this->baseUrl('img/'.$myHouse->picture1)."' width = 200px height = 100px></td></a><td class = 'data'>" . $myHouse->location . "</td><td class = 'data'>" . number_format($myHouse->price) . "</td><td class = 'data'>" . number_format($myHouse->sq_ft) . "</td><td class = 'data'>
									                         <button  type = 'submit'  formaction = '".$this->url(array('controller' => 'owner',
		                                                     'action' => 'update', 'idHouse' => $myHouse->id), 'default', true)."' >Update</button></td><td class = 'data'><button type = 'submit' formaction = '".$this->url(array('controller' => 'owner',
		                                                     'action' => 'delete', 'idHouse' => $myHouse->id), 'default', true)."'>Delete</button></td></tr>";
			
			
		}
		
		
		
		
		?>
		
		
		
		</table>
                
               
                
                </form>
                
                
                
                
                </div>
            </div>
        </div>

        

    </div>
   
    

   


		

	</div>


























