

	<div id="main">
		


    <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <form>
                  <table id = "myTable">
					  
					  <tr><th class = "myHeader">Question</th><th class = "myHeader">Answer</th><th colspan = 2 class = "myHeader">Options</th></tr>
					  
					  
					  <?php
					  
					  
					  foreach ($this->faqList as $faq) {
						  
						  echo "<tr><td class = 'data'>".$faq->question."</td><td class = 'data'>".$faq->answer."</td><td class = 'data'><button type = 'submit' formaction = '".$this->url(array('controller' => 'admin',
		                                                     'action' => 'updatefaq', 'faqId' => $faq->id), 'default', true)."' >Update</button></td>
						  <td class = 'data'><button type = 'sumbit' formaction = '".$this->url(array('controller' => 'admin',
		                                                     'action' => 'deletefaq', 'faqId' => $faq->id), 'default', true)."' >Delete</button></td></tr>";
						  
					  }
					  
					  
					  
					  ?>
                  
                  
                  
                  
                  
                  </table>
                  
                  </form>
                  
                </div>
               
               
                
            </div>
        </div>

        

    </div>
   
    

   


		

	</div>


























