

	<div id="main">
		


    <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
					
					<center>
						<form>
							
							<button id = "clearButton" type = "submit" formaction = "<?php echo $this->url(array('controller' => 'admin',
		                                                     'action' => 'clearLogs'), 'default', true);  ?> ">Clear</button>
							
							<br><br>
						
						
						</form>
						
					<table id = "myTable">
						<tr><th class = "myHeader">User</th><th class = "myHeader">Action</th><th class = "myHeader">Role</th><th class = "myHeader">Date</th></tr>
					
					<?php
					
					foreach ($this->logFileList as $logFile) {
						
						echo "<tr><td class = 'data'>".$logFile->user."</td><td class = 'data'>".$logFile->action."</td>
						 <td class = 'data'>".$logFile->object."</td><td class = 'data'>".$logFile->date."</td></tr>";
						
						
					} 
					
					
					
					?>
					
					</table>
					</center>
                    
                  
                  
                </div>
               
               
                
            </div>
        </div>

        

    </div>
   
    

   


		

	</div>


























