
<div id = "main">
    <div class="container">

        

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
					
					<h6 class='intro-text text-center'>Update Faq Form</h6>
                    <hr>
					
					
					<center>
					
                    <?php 
              	
						echo $this->updateFaqForm;
						

						
				 ?>
				 

				 
				 
				 </center>
				 
                    
                   </div>
            </div>
        </div>

    </div>


    


</div>
