

	<div id="main">
		


    <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <center>
						

						<form>
                    <table id = "myTable">
						<tr><th class = "myHeader">Username</th><th class = "myHeader">Password</th><th class = "myHeader">Role</th><th class = "myHeader">Name</th><th class = "myHeader">Surname</th><th class = "myHeader">Email</th><th class = "myHeader">Cell</th><th class = "myHeader">Option</th></tr>
                    <?php
                    
                    foreach ($this->usersList as $user)  {
						
						
						echo "<tr><td class = 'data'>" .$user->username.  "</td><td class = 'data'>".$user->password."</td>
						<td class = 'data'>".$user->role."</td><td class = 'data'>"
						.$user->name. "</td><td class = 'data'>".$user->surname."</td><td class = 'data'>".$user->email."</td>
						<td class = 'data'>".$user->cell."</td><td class = 'data'><button type = 'submit' formaction = '".$this->url(array('controller' => 'admin',
		                                                     'action' => 'deleteuser', 'userId' => $user->id), 'default', true)."' >Delete</button></td></tr>";
						
						
						
					} 
                    
                    
                    ?>
                   </table>
                   </form>
                  </center>
                </div>
               
               
            </div>
        </div>

        

    </div>
   
    

   


		

	</div>


























